version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.3.1
  browser-tools: circleci/browser-tools@2.1.2
  cypress: cypress-io/cypress@dev:alpha

jobs:
  install-and-persist:
    executor:
      name: cypress/default
    steps:
      - cypress/install:
          working-directory: examples/angular-app
          cypress-cache-key: cypress-cache-{{ arch }}-{{ checksum "examples/angular-app/package.json" }}
          include-branch-in-node-cache-key: true
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache/Cypress
            - project
  run-ct-tests-in-chrome:
    executor:
      name: cypress/default
    steps:
      - run: echo "This step assumes dependencies were installed using the cypress/install job"
      - attach_workspace:
          at: ~/
      - browser-tools/install_chrome
      - cypress/run-tests:
          working-directory: examples/angular-app
          cypress-command: "npx cypress run --component --browser chrome"
  run-ct-tests-in-chrome-for-testing:
    executor:
      name: cypress/default
    steps:
      - run: echo "This step assumes dependencies were installed using the cypress/install job"
      - attach_workspace:
          at: ~/
      - browser-tools/install_chrome_for_testing
      - cypress/run-tests:
          working-directory: examples/angular-app
          cypress-command: "npx cypress run --component --browser chrome-for-testing"
  run-ct-tests-in-firefox:
    executor:
      name: cypress/default
    steps:
      - run: echo "This step assumes dependencies were installed using the cypress/install job"
      - attach_workspace:
          at: ~/
      - browser-tools/install_firefox
      - cypress/run-tests:
          working-directory: examples/angular-app
          cypress-command: "npx cypress run --component --browser firefox"
  run-ct-tests-in-edge:
    executor:
      name: cypress/default
    steps:
      - run: echo "This step assumes dependencies were installed using the cypress/install job"
      - attach_workspace:
          at: ~/
      - browser-tools/install_edge
      - cypress/run-tests:
          working-directory: examples/angular-app
          cypress-command: "npx cypress run --component --browser edge"

workflows:
  test_deploy:
    jobs:
      - cypress/run:
          name: Standard Npm Example
          working-directory: examples/npm-install
          cypress-cache-key: cypress-cache-{{ arch }}-{{ checksum "examples/npm-install/package.json" }}
          post-install: "npm run say-hello && npm run say-goodbye"
      - cypress/run:
          name: Custom Node Version Example
          working-directory: examples/npm-install
          cypress-cache-key: cypress-cache-{{ arch }}-{{ checksum "examples/npm-install/package.json" }}
          node-version: "22.17.0"
          post-install: |
            if ! node --version | grep -q "22.17.0"; then
                echo "Node version 22.17.0 not found"
                exit 1
            fi
      - cypress/run:
          name: Yarn Example
          working-directory: examples/yarn-install
          cypress-cache-key: cypress-cache{{ arch }}-{{ checksum "examples/yarn-install/package.json" }}
          post-install: "npx cypress install"
          package-manager: "yarn"
      - cypress/run:
          name: Pnpm Example
          working-directory: examples/pnpm-install
          cypress-cache-key: cypress-cache{{ arch }}-{{ checksum "examples/pnpm-install/package.json" }}
          post-install: "pnpm cypress install"
          package-manager: "pnpm"
      - cypress/run:
          name: Custom Install Example
          working-directory: examples/custom-install
          install-command: npm run custom-install
          cypress-cache-key: cypress-cache-{{ arch }}-{{ checksum "examples/custom-install/package.json" }}
      - cypress/run:
          name: Wait On Example
          working-directory: examples/wait-on
          cypress-cache-key: cypress-cache-{{ arch }}-{{ checksum "examples/wait-on/package.json" }}
          start-command: npm start
          # wait-on will wait for the server to be ready before running the tests
          # -v only needed for demonstration purposes
          cypress-command: npx wait-on@latest http://localhost:8080 -v && npx cypress run
      - cypress/run:
          name: Angular Application
          working-directory: examples/angular-app
          cypress-cache-key: cypress-cache-{{ arch }}-{{ checksum "examples/angular-app/package.json" }}
          start-command: "npm run start"
          cypress-command: "npx wait-on@latest http://localhost:4200 && npx cypress run --browser chrome"
          install-browsers: true
      # - cypress/run:
      #     name: Run CT in Parallel
      #     working-directory: examples/angular-app
      #     cypress-cache-key: cypress-cache-{{ arch }}-{{ checksum "examples/angular-app/package.json" }}
      #     cypress-command: "npx cypress run --component"
      - cypress/run:
          name: Verify skip-checkout
          working-directory: examples/angular-app
          cypress-cache-key: cypress-cache-{{ arch }}-{{ checksum "examples/angular-app/package.json" }}
          cypress-command: "npx cypress run --component"
          pre-steps:
            - checkout
      # - cypress/run:
      #     name: Verify resource_class config works
      #     working-directory: examples/angular-app
      #     cypress-cache-key: cypress-cache-{{ arch }}-{{ checksum "examples/angular-app/package.json" }}
      #     cypress-command: "npx cypress run --component"
      #     resource_class: smalls
      #     pre-steps:
      #       - checkout
      - install-and-persist:
          name: Install & Persist
      - run-ct-tests-in-chrome:
          name: Run CT Tests in Chrome
          requires:
            - Install & Persist
      - run-ct-tests-in-chrome-for-testing:
          name: Run CT Tests in Chrome for Testing
          requires:
            - Install & Persist
      - run-ct-tests-in-firefox:
          name: Run CT Tests in Firefox
          requires:
            - Install & Persist
      - run-ct-tests-in-edge:
          name: Run CT Tests in Edge
          requires:
            - Install & Persist
